<?php

namespace Database\Factories\Traits;

use Illuminate\Support\Str;

trait FactoryTrait
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<\Illuminate\Database\Eloquent\Model|TModel>
     */
    public function modelName()
    {
        $resolver = static::$modelNameResolver ?? function (self $factory) {
            $namespacedFactoryBasename = Str::replaceLast(
                'Factory', '', Str::replaceFirst(static::$namespace, '', get_class($factory))
            );

            $factoryBasename = Str::replaceLast('Factory', '', class_basename($factory));
            $appNamespace = static::appNamespace();

            return class_exists($namespacedFactoryBasename)
                ? $namespacedFactoryBasename
                : $appNamespace.$factoryBasename;
        };

        return $this->model ?? $resolver($this);
    }

}
