version: '3.5'

services:
  laravel-prueba-web:
    container_name: laravel-prueba-web
    build:
      context: ./etc/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - laravel-prueba-be
    networks:
      - laravel-prueba-network

  laravel-prueba-be:
    container_name: laravel-prueba-be
    build:
      context: etc/php
      args:
        UID: $U_ID
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=laravel-prueba

    volumes:
      - ./:/appdata/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - laravel-prueba-db
    networks:
      - laravel-prueba-network

  laravel-prueba-db:
    container_name: laravel-prueba-db
    build:
      context: ./etc/database
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: laravel-prueba_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - laravel-prueba-db-data:/var/lib/mysql
    networks:
      - laravel-prueba-network

volumes:
  laravel-prueba-db-data:

networks:
  laravel-prueba-network:
    external: true
